<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_From HEAT</name>
   <tag></tag>
   <elementGuidId>133adc8f-0ebd-42d4-8536-22bc27ae2335</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate'])[1]/following::div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8a7004a6-cde1-41f9-a34d-9c2f1b10b8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>561033b9-3a24-49a8-9c2d-af61ee33aced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>078a9a31-5dda-45a8-8011-544de54586f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>react-aria-1</value>
      <webElementGuid>ac57ead6-0436-4e0f-b825-3cd95baf9665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex min-w-fit flex-1 cursor-pointer select-none space-x-[18px] rounded-[5px] px-[12px] py-[10px] outline-none bg-blue-500/10</value>
      <webElementGuid>142e7bc6-0230-4310-b2db-955490e385fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3b3c78b0-b8d3-42f7-8fd3-a2b7173e7e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f680f0e1-ee15-43a5-a9ef-f7978b9e6001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From HEAT</value>
      <webElementGuid>050aed4d-69a7-400d-88cf-911bd6686293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;group rounded-[8px] border border-black/10 bg-white bg-clip-padding text-slate-700 shadow-lg&quot;]/div[@class=&quot;min-w-[170px] p-[6px] outline-none&quot;]/div[@class=&quot;flex min-w-fit flex-1 cursor-pointer select-none space-x-[18px] rounded-[5px] px-[12px] py-[10px] outline-none bg-blue-500/10&quot;]</value>
      <webElementGuid>9bd83753-e96e-4884-8277-a129f41040eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate'])[1]/following::div[5]</value>
      <webElementGuid>a78904a0-15ad-4f94-81e9-262056f79690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save progress'])[1]/following::div[5]</value>
      <webElementGuid>0d91dc1b-367c-4063-8afb-ded652f3fb6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div</value>
      <webElementGuid>0997beb1-a02b-4268-9d6a-35e14a699620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'From HEAT' or . = 'From HEAT')]</value>
      <webElementGuid>f0ebd885-fc6a-4a3f-b1de-12d254dff746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
