<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Page_react-aria148752833-r4t</name>
   <tag></tag>
   <elementGuidId>21b412f2-e55b-4d40-8466-d3ad0af9538a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='react-aria148752833-:r4t:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>355dfba7-3345-4847-844a-66e6497cb787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47f92410-b46a-4bb0-92a9-a20ec96f0355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Vendor</value>
      <webElementGuid>5cfda4ce-fad3-4263-a5ab-ce3c4902839c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-aria148752833-:r4t:</value>
      <webElementGuid>7ec6355c-d3e1-4ca3-a1b5-e6c910cc9a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Vendor</value>
      <webElementGuid>44862b3a-9ed7-4a61-9fb1-953bb52a416a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full flex-1 bg-transparent px-[10px] py-[5px] outline outline-0 placeholder:text-neutral-500</value>
      <webElementGuid>47aff7d8-1107-4fcf-98c6-43221441c24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>87dfefd0-b456-4d41-ad97-cdd4d3b78329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria148752833-:r4t:&quot;)</value>
      <webElementGuid>c77961b7-0841-45a4-82c4-4462f1d58dc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='react-aria148752833-:r4t:']</value>
      <webElementGuid>7966b994-3b25-478a-9da4-d0a7eb8e044b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='packet-details']/div[2]/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>d4d9fb32-cbd2-4c91-a4ee-8f32967d9f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>276b2602-a37a-43fe-b43a-f382bcae9c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Vendor' and @id = 'react-aria148752833-:r4t:']</value>
      <webElementGuid>1c34bdd5-adf0-4762-9ffe-5e1ef6936420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
