<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Page_react-aria1827729712-rip</name>
   <tag></tag>
   <elementGuidId>9ebd989e-5132-440f-9196-9430c0e91104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[5]/div/section/div/form/div[2]/div[1]/div/div[5]/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8445175-c78c-46f1-898e-78d582b2926f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0aa1a29b-4802-44dc-b521-c43c63b3270a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Size</value>
      <webElementGuid>7c94b572-76a4-4a54-9eb1-5ed30a29262d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-aria1827729712-:rip:</value>
      <webElementGuid>72d67b5f-f2be-4f70-8dbd-6738ba161d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Size</value>
      <webElementGuid>d8d7f371-5fc5-4175-9a89-21204794a710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full flex-1 bg-transparent px-[10px] py-[5px] outline outline-0 placeholder:text-neutral-500</value>
      <webElementGuid>fe15b759-bd62-4c12-a275-994bf24a0444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovered</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>24d3649f-ed56-4468-b79a-d3c8f6a52b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-aria1827729712-:rip:&quot;)</value>
      <webElementGuid>d001fdc9-d259-43d8-82e1-9fb9b705f450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='react-aria1827729712-:rip:']</value>
      <webElementGuid>02224f74-f3b9-48e1-9adf-94fc5e5065b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='packet-details']/div[2]/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>5bec807a-766d-4ae3-a11e-788c101cef07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>c5356580-fd22-4a5d-abd2-76bcbd2442b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Size' and @id = 'react-aria1827729712-:rip:']</value>
      <webElementGuid>31365d1e-8932-40f8-b5b1-e6521757c800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
